### ISSUE TITLE
Redesign the feature "Change workspace" (main interface)

### ISSUE THREAD

**Issue by tiagofml** [ufopleds/DengueME#11]
Redesign the feature "Change workspace" (main interface)
- [x] Specify the behavior and the design of GUI using low-fidelity prototypes
- [x] Review the specification
- [x] Refactor the source code to develop the changes and improvements defined by the specification

# Specification

## User Storie
AS user, I WANT to change my workspace SO THAT I can better organize related projects into one same workspace. 
See other templates <https://en.wikipedia.org/wiki/User_story>.

## General behavior
**Preconditions:** a workspace (directory) is currently loaded and their folders are presented in the Project Explorer View
**Postconditions:** a new workspace (directory) is loaded and the Project Explorer View is updated with their folders
**Rules / restrictions:** 
- DengueME must verify if the path corresponds to valid and existing directory in the system OR it must deny users to directly insert the path in the text field 

### Basic Flow
1. The user access the "Change Workspace" feature: Tools -> Change Workspace 
2. The "Change Workspace" window is opened, with no warning/error message. The path of the current workspace is shown.
3. User chooses the new workspace (directory) using the file explorer feature or manually typing the path.
4. User clicks on "OK" button
5. The current workspace is updated to the directory chosen by user and the Project Explorer View is updated to show the existing folders inside this directory.

### Alternative Flow: user types a wrong path 
3.1. User chooses the new workspace (directory) manually typing a path which does not correspond to an existing folder.
3.2. The "OK" button is disabled and an error message is presented.

### Alternative Flow: user cancel the operation
N.1. User clicks on "Cancel" or "X"
N.2. The "Change Workspace" window is closed and the user returns to the main interface

### Alternative Flow: chosen directory as default workspace
3.1. User selects the option to use the chosen directory as the default workspace
3.2. User clicks on "OK"
3.3. The current workspace is updated to the directory chosen by user and the Project Explorer View is updated to show the existing folders inside this directory. The path of the chosen directory is saved in DengueME settings as the default workspace.

### Prototype
![screen shot 2017-10-24 at 11 19 24 am](https://user-images.githubusercontent.com/1895217/31945192-3460f51c-b8ad-11e7-940d-9abf1d2b821d.png)

### Guildelines
- The window is modal and opened with auto-focus
- When the window is opened, the default focus is on the textfield widget.
- Clear the selection of the project view after changing the workspace.

### Messages and labels (english | portuguese)
- Window Title: Change Workspace | Alterar o Espaço de Trabalho
- Title: Workspace | Espaço de trabalho
- Workspace (Path): | Espaço de trabalho (Caminho):
- Subtitle: DengueME will save your projects inside a folder called workspace.  Choose the folder to be used as workspace. | O DengueME armazenará seus projetos dentro de uma pasta chamada "espaço de trabalho". Escolha a pasta que será usada para essa finalidade.
- Checkbox option: Use as default workspace. | Usar como espaço de trabalho padrão.
- Error message (wrong path): This folder does not exist. | Essa pasta não existe.

**Comment by tiagofml** [comment]
@Guelmisp The window is not translated to Portuguese.

![image](https://user-images.githubusercontent.com/1923107/31085482-9ff8a91a-a76d-11e7-8b93-114b0d1a3f90.png)

**Comment by tiagofml** [comment]
@Guelmisp The translation problem must be addressed in issue #13.

**Comment by tiagofml** [comment]
@Guelmisp 
1) Please update the error message text and layout.

![image](https://user-images.githubusercontent.com/1923107/31087872-1698f60e-a775-11e7-8d14-430421d7edaf.png)

2) The window must be opened with the focus (auto-focus option)

3) If user type a valid folder, the focus must be changed to the "OK" button.

4) The window size must be fixed with proper dimensions, without allowing resize. (630 x 290)

![image](https://user-images.githubusercontent.com/1923107/31089214-a4b7ac6a-a779-11e7-8427-0c0b9dfc699d.png)


5) Fix the tab order, follow this picture: 
![image](https://user-images.githubusercontent.com/5274118/31089406-4a7c383c-a77a-11e7-897a-a5468425c61f.png)

**Comment by miguelspe** [comment]
The required changes were addressed by [PR]#20.
1. The error message was updated.
2. When the user types a valid folder, the OK button will be with the focus.
3. Size is now 630x290 and it can't be resizable anymore.
4. Tab order was fixed as suggested.

**Comment by tiagofml** [comment]
@Guelmisp Please check the following problems
- layout of the window is not consistent - size and alignment (e.g. see the New project window)
![image](https://user-images.githubusercontent.com/1923107/31865565-61cbadbc-b74f-11e7-9d5b-313aaa6af9df.png)

- please check the error messsage (previously reported) and other messages and labels of the GUI, which are different from the specification
![image](https://user-images.githubusercontent.com/1923107/31865492-8086c904-b74e-11e7-9f2f-d528665c9e78.png)

- update the specification with the final version of the GUI
