### ISSUE TITLE
Redesign the feature "Rename Model" (main interface)

### ISSUE THREAD

**Issue by tiagofml** [ufopleds/DengueME#12]
Redesign the feature "Rename Model" (main interface)
- [x] Specify the behavior and the design of GUI using low-fidelity prototypes
- [x] Review the specification
- [x] Refactor the source code to develop the changes and improvements defined by the specification

# Specification

## User Storie
AS user, I WANT to rename a model SO THAT I can better organize the project.
See other templates <https://en.wikipedia.org/wiki/User_story>.

## General behavior
**Preconditions:** a model is selected (Project Explorer View) or opened (Editor) and it has a valid name.
**Postconditions:** 1) the model (XML file) is updated with a valid new name, 2) the model script folder is updated with a valid new name.
**Rules / restrictions:** 
- a name is valid if it contains only alphanumeric chars, hyphen (-) and/or underscore (_).

### Basic Flow
1. The user access the "Rename Model" feature: File -> Rename | Toolbar icon | F2 | Context menu
2. The "Rename Model" window is opened (auto-focus), with no warning/error message and with "OK" button disabled. 
3. User types a valid name for the model.
4. The "OK" button is enabled.
5. User clicks on "OK" or user types ("ENTER") on keyboard.
5. The focus must be on the renamed model on the project tree view.
6. The model (XML file) is updated with the new name, and the model script folder is also updated. The "Rename Model" window is closed and the user returns to the main interface.

### Alternative Flow: user cancel the operation
N.1. User clicks on "Cancel" or "X"
N.2. The "Rename Model" window is closed and the user returns to the main interface

### Alternative Flow: name is invalid
3.1. User types an invalid name for the model.
3.2. A warning message is presented.

### Alternative Flow: name already exists
3.1. User types a name of a model that already exists in the same project.
3.2. A warning message is presented.

### Prototype
![image](https://user-images.githubusercontent.com/1923107/31865269-1088cd76-b74b-11e7-8339-8cedf934ccc5.png)

### Guildelines
- The window is modal and opened with auto-focus
- When the window is opened, the default focus is on the textfield widget (Name).
- After opening and closing the Rename Model window, the GUI must maintain the selection (project view tree) on the file which is being renamed.
- The "OK" button has greater priority to receive focus than the "Cancel" button.

### Messages and labels (english | portuguese)
- Window Title: Rename Model | Renomear Modelo
- Title: Model name | Nome do modelo
- Subtitle: Define a new name for your model. | Defina um novo nome para o modelo.
- Warning (invalid name): The model name can contain only alphanumeric chars, hyphen (-) and / or underscore (\_). | O nome do modelo pode conter somente caracteres alfanuméricos, hífen (-) e / ou sublinhado (\_). 
- Warning (duplicated name): A model with this name already exists in current project. | Um modelo com esse nome já existe no projeto atual.

**Comment by tiagofml** [comment]
@Guelmisp The window is not translated to Portuguese.
![image](https://user-images.githubusercontent.com/1923107/31085723-53e95640-a76e-11e7-9a29-3babf55bc52e.png)

**Comment by tiagofml** [comment]
@Guelmisp The translation problem must be addressed in issue #13.

**Comment by tiagofml** [comment]
@Guelmisp 

1) The window size must be fixed with proper dimensions, without allowing resize. (630 x 290)

2) Update the visual feedback of the focus when user type a valid name. For example, if I type a valid name and press "Enter", the action of "OK" button will be performed (fine), but the visual feedback is wrong (it seems that the "Cancel" button has the focus)

![image](https://user-images.githubusercontent.com/1923107/31089448-7ffc60cc-a77a-11e7-9231-66d86ba4b00a.png)

3) Check the tab order

**Comment by saraiva3** [comment]
The rename window has a small problem in its interface, the buttons should be self containned in the layout, so it moves all together 

![image](https://user-images.githubusercontent.com/5274118/31093980-dd40db00-a789-11e7-965b-3f2a0d36ded1.png)

**Comment by miguelspe** [comment]
The required changes were addressed by #20 pull request.

1. The window size is now 630x290.
2. focus is now updated when a user types a valid name.
3. The Window was fixed and the problem reported by @saraiva3 was fixed.

**Comment by tiagofml** [comment]
@Guelmisp Please check the following problems:
- check the message for invalid name
![image](https://user-images.githubusercontent.com/1923107/31865316-ddc3c0a2-b74b-11e7-8776-7eca44e33248.png)
- BUG: after performing a rename operation without change the name, the rename will be disabled but should not be since the model is selected. How to reproduce: 1) select an existing model - the window will be opened, 2) type space and then backspace, thus, the name will remains the same - the "OK" button will be enabled, 
![image](https://user-images.githubusercontent.com/1923107/31865352-8900250a-b74c-11e7-9d5e-a5d47364f22d.png)

3) press "OK" - the model has the focus, but the Rename feature is disabled. Actually, it seems that the file does not have the focus, despite the visual feedback. The same problem happens when the window is opened and closed using "Cancel' (1) select a model, 2) press F2, 3) click "Cancel").
![image](https://user-images.githubusercontent.com/1923107/31865381-0eb71c30-b74d-11e7-82b0-6f38d998208a.png)

A suggestion to solve this is to not enable the "OK" button if the name remains the same. And remember and mantain the selection in the Project Explorer view.
