### ISSUE TITLE
Redesign the feature "New Project" (main interface)

### ISSUE THREAD

**Issue by tiagofml** [ufopleds/DengueME#15]
Redesign the feature "New Project" (main interface)
- [x] Specify the behavior and the design of GUI using low-fidelity prototypes
- [x] Review the specification
- [x] Refactor the source code to develop the changes and improvements defined by the specification

# Specification

## User Storie
AS user, I WANT to create a new project SO THAT I can create models and simulations. 
See other templates <https://en.wikipedia.org/wiki/User_story>.

## General behavior
**Preconditions:** - 
**Postconditions:** a new directory with the defined name is created inside the workspace directory.
**Rules / restrictions:** 
- a name is valid if it contains only alphanumeric chars, hyphen (-) and/or underscore (_).

### Basic Flow
1. The user access the "New Project" feature: File -> New Project | Toolbar icon | Control + O
2. The "New Project" window is opened, with no warning/error message and with "Create" button disabled.
3. User types a valid name for the new project.
4. The "Create" button is enabled.
5. User clicks on "Create" or press "Enter".
6. A new directory with the name defined by the user is created inside the directory of the workspace. The "New Project" window is closed and the user returns to the main interface.

### Alternative Flow: user cancel the operation
N.1. User clicks on "Cancel" or "X"
N.2. The "New Project" window is closed and the user returns to the main interface

### Alternative Flow: name is invalid
3.1. User types an invalid name for the new project.
3.2. A warning message is presented.

### Alternative Flow: name already exists
3.1. User types a name of a project that already exists in the workspace.
3.2. A warning message is presented.

### Alternative Flow: name is valid and the new model option is selected 
6.1. A new directory with the name defined by user is created inside the directory of the workspace.  The "New Project" window is closed and the "New Model" window is opened.

### Prototype
![screen shot 2017-10-24 at 10 42 02 am](https://user-images.githubusercontent.com/1895217/31943617-fc9b41a0-b8a7-11e7-9fb4-b3078eb0005f.png)

### Guildelines
- The window is modal and opened with auto-focus
- After opening a new model window, the GUI must clear the selected itens on project view tree.
- When the window is opened, the default focus is on the textfield widget (Project name).
- The "Create" button has greater priority to receive focus than the "Cancel" button, which means that if everything is fine (e.g. name is valid and unique) and user types "Enter", the "Create" must be performed.

### Messages and labels (english | portuguese)
- Window Title: New Project | Novo Projeto
- Title: Project name | Nome do projeto
- Subtitle: Define a name for your new project. | Defina um nome para o novo projeto.
- Default textfield inpute: e.g. myproject | ex. meuprojeto
- Checkbox option: I would like to create a new model inside this project. | Gostaria de criar um novo modelo para este projeto.
- Warning (invalid name): The project name can contain only alphanumeric chars, hyphen (-) and / or underscore (\_). | O nome do projeto pode conter somente caracteres alfanuméricos, hífen (-) e / ou sublinhado (\_). 
- Warning (duplicated name): A project with this name already exists in current workspace. | Um projeto com esse nome já existe no espaço de trabalho atual.

**Comment by tiagofml** [comment]
@Guelmisp 

1) The window size must be fixed with proper dimensions, without allowing resize. (630 x 290)

2) Update the focus and the visual feedback of the focus when user type a valid name. Please see the GUI guidelines in the issue description.

3) Check the tab order.

**Comment by miguelspe** [comment]
The required changes were addressed by #20 pull request.

1. The window size is now 630x290.
2. focus is now updated when a user types a valid name.
3. Tab order revised.

**Comment by tiagofml** [comment]
@Guelmisp Some required changes
- Replace the button label "OK" by "Create"
- Remove "." from the subtitle

and something to discuss and decide
- DengueME GUIs must be consistent, e.g. 1) some warning/error messages has a "." at the end of phrase, while others do not (see #16) ; 2) icons used by windows are different (see #15 and #16)
