### ISSUE TITLE
[BUG] Users can change the folder name with the Rename Model feature, but it should not be possible to do it

### ISSUE THREAD

**Issue by tiagofml** [ufopleds/DengueME#18]
Users can change the folder name with the Rename Model feature, but it should not be possible to do it.

**OS:** Windows 7
**Version:** DengueME v0.7.0* (built from the source-code avaiable on master branch)

**How to reproduce:**
1. Open DengueME in a workspace with some existing projects.
2. Click on a model without open it.
![image](https://user-images.githubusercontent.com/1923107/31131605-f8161006-a830-11e7-9708-9910b26a8b28.png)
3. Use the keyboard (arrow up and down) to navigate in the Project Explorer view, and select the project (folder)
![image](https://user-images.githubusercontent.com/1923107/31131650-15dc3854-a831-11e7-8e6e-9ce66907027a.png)
4. Press F2 (or Rename in toolbar or File menu)
5. DengueME will open the Rename Model window, but it should not do it.
![image](https://user-images.githubusercontent.com/1923107/31131690-34148646-a831-11e7-8dec-00382220274f.png)
6. Change the name of the "model" (actually is the script folder in this example) and press "OK".
![image](https://user-images.githubusercontent.com/1923107/31131774-796d529a-a831-11e7-89aa-24de1baa04ca.png)
7. The folder possible will be renamed, but this is not a desirable behavior. (Win7 prevents the rename operation because the folder is current being used).
![image](https://user-images.githubusercontent.com/1923107/31131879-bfb68564-a831-11e7-9f43-2761e2aee916.png)

**Comment by miguelspe** [comment]
The PR #21 will fix this issue.
