### ISSUE TITLE
[BUG] When the keyboard is used to navigate in Project Explorer, sometimes the rename feature is not accessible

### ISSUE THREAD

**Issue by tiagofml** [ufopleds/DengueME#19]
When the keyboard is used to navigate in Project Explorer, sometimes the rename feature is not accessible.

**OS:** Windows 7
**Version:** DengueME v0.7.0* (built from the source-code avaiable on master branch)

**How to reproduce:**
1. Open DengueME in a workspace with some existing projects.
2. Click on a project - the Rename feature will be deactivated as expected.
![image](https://user-images.githubusercontent.com/1923107/31132493-4dfc87dc-a833-11e7-9fcb-7a2908a9704e.png)
3. Use the keyboard (arrow up and down) to navigate in the Project Explorer view, and select a model. The Rename feature is still deactivated, but it should be active in this context, since a model was selected. 
![image](https://user-images.githubusercontent.com/1923107/31132540-6aa2c888-a833-11e7-9ce1-4fb26d038030.png)

An observation: the Delete feature keeps active in all steps, as DengueME allows users to delete models and projects. However, as we avoid renaming a project, this feature must be deactivated if a project is selected (using mouse or keyboard) and activated if a model is selected (using mouse or keyboard).

**Comment by miguelspe** [comment]
The pull request #21 should fix this problem.
