### ISSUE TITLE
[BUG] New Model does not show all models when using Portuguese interface

### ISSUE THREAD

**Issue by miguelspe** [ufopleds/DengueME#34]
[BUG] New Model does not show all models when using Portuguese interface. Moreover, the options of combobox are not translated to Portuguese.
Issue related to #16 and #13. 

OS: Windows 7
Version: DengueME v0.7.1 (built from the source-code available on dev branch)

How to reproduce (using Portuguese interface):
1. Arquivo -> Novo Modelo, click on "Próximo"
![image](https://user-images.githubusercontent.com/1923107/32146358-5cfb602a-bcbd-11e7-8214-301991356fd6.png)

2. By default, the option "Todas" from "Categoria" is selected. However, no model is presented. The models are available in DengueME Lib and should be presented.
![image](https://user-images.githubusercontent.com/1923107/32146376-a118fb96-bcbd-11e7-8cbe-b2038b4422ee.png)

3. Another problem is that the options of "Categoria" are not translated to Portuguese.
![screen shot 2017-10-27 at 4 22 21 pm](https://user-images.githubusercontent.com/1895217/32119151-191ebd92-bb33-11e7-95ff-6dcbd34a4829.png)

**Comment by tiagofml** [comment]
In future, the list of categories will be available and read through the XML configuration file.
