### ISSUE TITLE
Redesign the feature "Change interface language" (Options interface)

### ISSUE THREAD

**Issue by tiagofml** [ufopleds/DengueME#50]
Redesign the feature "Change interface language" (Options interface)
- [x] Specify the behavior and the design of GUI using low-fidelity prototypes
- [x] Review the specification
- [x] Refactor the source code to develop the changes and improvements defined by the specification

# Specification

## User Storie
AS user, I WANT to change the language of the interface SO THAT I can better understand and use the software. 
See other templates <https://en.wikipedia.org/wiki/User_story>.

## General behavior
**Preconditions:** the interface is currently presented in a language L1 (e.g. English).
**Postconditions:** the interface is loaded with the language L2 (e.g. Portuguese), selected by user.
**Rules / restrictions:** 
- All software interfaces must be loaded in the language selected by the user. 
- The documentation of models, when available, must be loaded in the language selected by the user.
- English is the default interface language.
- There must be two different status (system variables) related to language: 1) current language of interface ("gui_current_language"), 2) language selected by user ("gui_user_language"). DengueME always load the language interface based on the value of "gui_current_language". If user change the language without close+reopen DengueME, their values will be different. When starting DengueME, the system must check if the "gui_current_language" is equal to "gui_user_language". If they are equal, no action is required. If they are different, the system must update "gui_current_language" to be equal to "gui_user_language".

### Basic Flow
1. The user access the "Change interface language" feature: Tools -> Options
2. The "Options" window is opened in "General" tab, with no warning/error message. The current language of interface is selected (e.g. English) ("gui_current_language" = "english").
3. User changes the language (e.g. Portuguese).
4. A warning message is presented informing that the software must be closed and reopened.. 
5. User clicks on "OK" button ("gui_user_language" = "portuguese").

### Alternative Flow: user cancel the operation
2.1. User clicks on "Cancel" or "X"
2.2. The "Options" window is closed without saving configuration data, and the user returns to the main interface

### Prototype
![image](https://user-images.githubusercontent.com/1923107/35400054-f2d1f168-01dc-11e8-87cd-2f38196e3b64.png)

### Guildelines
- The selected language in the widget must always be consistent with the current language of the interface. E.g. if the current language is English, then, English must be presented as the selected item in the widget.
- User have to confirm the change of the language (e.g. "OK" button).
- The window ("Options") must present a message informing user that the software has to be closed and reopened for the change to take effect.

### Messages and labels (english | portuguese)
- Label: Language | Idioma
- Warning message (restart required): Please restart DengueME for the changes to take effect. | Por favor, reinicie o DengueME para que as mudanças sejam aplicadas.
- Warning message (inconsistent languages): There is a pending update: the interface will change to the language **XYZ** in the next initialization. | Existe uma atualização pendente: a interface será atualizada para o idioma **XYZ** na próxima inicialização.
- Warning message (inconsistent languages): There is a pending update: in the next initialization the interface will change to the language **XYZ**. | Existe uma atualização pendente: na próxima inicialização a interface será atualizada para o idioma **XYZ**.

**Comment by miguelspe** [comment]
What about the name of the language (names in Portuguese and English)? 

For example, when the current language is in English if the user wants to change it the combo box will display (English and Portuguese) to be selected.

However, if the language defined is Portuguese (the text will be English and Portuguese instead of Inglês e Português in pt-br). 

Were going to translate that?
