### ISSUE TITLE
DengueMe installation

### ISSUE THREAD

**Issue by gafap** [ufopleds/DengueME#53]
Hi all, 
thanks for DENGUEME. We are trying to sue it in a project to predict dengue headcounts. But I'm having troubles installing the software. I followed the steps, installed TerraMe (2.0-RC-7) and then I donwloaded the folder DengueMEv071 and extract it.
But when I want to run a model I get an error saying "failed to start interpreter". I have seen issue number 6, but it is not clear to me. Where should I set the interpreter path to? do i need to install R as well?
thank you for the help, 
best regards, 
g

**Comment by saraiva3** [comment]
Hello @gafap,

You dont need to install R to run a TerraME model, there are two things that may be happening:

1) Check if the model that you choose to run is indeed a TerraMe model.
2) Check if the interpreter is configured under options->run(See picture). To make sure, click in  browse and configure the path to the bin folder of TerraME. By default it tries to use the SO paths, but probably is not finding it.

![image](https://user-images.githubusercontent.com/5274118/41850089-b9420886-7859-11e8-97c6-0e2f8c14516d.png)

Sorry for that.

**Comment by gafap** [comment]
Hello @saraiva3 , 

Thanks a lot for your quick answer. Indeed, I manually linked it to the TerraMe .exe file and now it works :)

**Comment by saraiva3** [comment]
Good, any problem fell free to contact us.

I hope the software helps you.

**Comment by andresouzaesilva** [comment]
Hello I am also wanting to test the software but where do I find Terra.exe, mine is the same as the figure but does not work, what else do I need to install and configure? Thanks
