### ISSUE TITLE
Spatial dynamic model for dengue

### ISSUE THREAD

**Issue by Spatial-R** [ufopleds/DengueME#6]
Hello, thanks for your development for the DengueME project.  After installing the software in my compute, there is an error when running the model with the default value:  failed to start interpreter. Is there any example for newer to use that software?
Another question is that how to use the DengueME to build a spatial dynamic model?

**Comment by saraiva3** [comment]
Hi, thank you for your feedback!!! 

All the base dengueME models make use of TerraME 1.6 (https://github.com/TerraME/terrame/releases/tag/1.6.0). You must install TerraME and configure the interpreter path under Options > Run.  Here is an example of where you should go, `http://imgur.com/a/wSLdK`

About the tutorials, I am working in a new tutorial, for now you can find some information on our Wiki https://github.com/ufopleds/DengueME/wiki ,sorry for the inconvenience. 

And last but not least, the dynamic model. DengueME makes uses of TerraME or RScript to run models. The models are not created by DengueME, only the interface is created via DengueME(Model Builder). For now we have only 3 models, but we are working to produce more. We also accept contributions, if you have the code/formula of a Dengue transmission or vector model, we can translate it to TerraML or R and put it into the dengueME library.

You can also find a tutorial to run a toy model SIR on our wiki (But TerraME must be installed first), https://github.com/ufopleds/DengueME/wiki/Example%3A-Sir-Basic-Model

I will keep this issue open, as soon as I finish all the tutorials, I will update the Wiki and close the issue.

Once again, thank you for the feedback, we appreciate it a lot !!!!!!

**Comment by gafap** [comment]
Hi Saraiva, 

I'm having troubles with this. I try to set a path for the interpreter as you suggest above, but do I need to install R for that? I have already installed TerraMe and DengueMe.
![interpreter](https://user-images.githubusercontent.com/40542599/41820295-665483b6-77c7-11e8-8f31-945a44ec8e85.PNG)

thanks!
g
